# version: "3.9"

# services:
#   rag-chatbot:
#     build: .
#     container_name: rag_chatbot
#     ports:
#       - "8501:8501"
#     volumes:
#       - .:/app
#     environment:
#       - GROQ_API_KEY=${GROQ_API_KEY}   # Load from .env
#     env_file:
#       - .env

version: "3.9"

services:
  rag-chatbot:
    build: .
    container_name: rag_chatbot
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=rag_chatbot
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: rag_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

